### ISSUE TITLE
Invalid formula when running 'brew tap'

### ISSUE THREAD

**Issue by JIACCOPU-ford** [NSHipster/homebrew-formulae#3]
I had this already installed, but I uninstalled and reinstalled. Then the error came up. Reproduced by doing:

`brew untap nshipster/formulae`
`brew tap nshipster/formulae`

This is reproducible with a fresh new install as well in a new laptop. 
Result:

<img width="794" alt="Screenshot 2020-03-09 at 12 30 16" src="https://user-images.githubusercontent.com/37177144/76213647-06feb080-6203-11ea-9020-f2ef26e1d61f.png">

**Comment by ndmeiri** [comment]
I'm also seeing the same issue. I had nshipster/formulae tapped. But upon untapping and then tapping again, I reproduce the error:

```shell
$ brew untap nshipster/formulae
Untapping nshipster/formulae...
Untapped 8 formulae (123 files, 70.4KB).
$ brew tap nshipster/formulae
==> Tapping nshipster/formulae
Cloning into '/usr/local/Homebrew/Library/Taps/nshipster/homebrew-formulae'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 85 (delta 13), reused 16 (delta 5), pack-reused 45
Unpacking objects: 100% (85/85), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/nshipster/homebrew-formulae/Formula/swift-format.rb
invalid attribute for formula 'nshipster/formulae/swift-format': version (nil)
Error: Cannot tap nshipster/formulae: invalid syntax in tap! 
```

I successfully `brew install`ed `nshipster/formulae/swift-format` at most a couple months ago, but the formula in [`swift-format.rb`](https://github.com/NSHipster/homebrew-formulae/blob/master/Formula/swift-format.rb) was most recently modified 8 months ago. Which suggests that the issue is not in the formula. Perhaps homebrew recently introduced a bug?

**Comment by ndmeiri** [comment]
I think this is a result of recent homebrew changes.

See Homebrew/homebrew-core#51073 and Homebrew/brew#7110 for details.

**Comment by ndmeiri** [comment]
Based on https://github.com/Homebrew/brew/issues/7110#issuecomment-594507593, it seems we'll need to add a version attribute to the SwiftFormat formula. Just sent #4 to do that.

**Comment by mywristbands** [comment]
Yes, I was running into this same issue as well. When I try running `brew install nshipster/formulae/swift-format`, I get the output:

```
Updating Homebrew...
==> Tapping nshipster/formulae
Cloning into '/usr/local/Homebrew/Library/Taps/nshipster/homebrew-formulae'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 85 (delta 13), reused 16 (delta 5), pack-reused 45
Unpacking objects: 100% (85/85), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/nshipster/homebrew-formulae/Formula/swift-format.rb
invalid attribute for formula 'nshipster/formulae/swift-format': version (nil)
Error: Cannot tap nshipster/formulae: invalid syntax in tap!
```
